### ISSUE TITLE
New

### ISSUE THREAD

**Issue by ETdoFresh** [ETdoFresh/TileMapCreator#10]
Start over... prompt user with following options....

- Start complete over
- Start over using same tileset
- Don't start over

[Should be a popup Window]

**Comment by onsclom** [comment]
Decided to start on this task before bed today. How is this design for the new popup window?

![image](https://user-images.githubusercontent.com/8485687/91694237-2aa31380-eb21-11ea-85b5-4746b5b5096a.png)

Some other ideas: 
- putting "New" as text in the top middle of the popup
- making cancel an 'X' in one of the top corners of the popup

I believe this will be the first implemented popup box, so whatever style we go with here I will make sure to follow with the future popup boxes.

**Comment by ETdoFresh** [comment]
Design is looking good, and I like both of those ideas. Put them in, and I'll test it out when ready! Thanks!

**Comment by onsclom** [comment]
Progress update:
* Implemented design ideas
* "Start completely over" reloads the current scene

![image](https://user-images.githubusercontent.com/8485687/91787765-760bff00-ebbf-11ea-9677-a6535fd46f20.png)

However I am having some difficulty with "Start over using same tileset". 

The two approaches I considered were:
1. Instead of completely reloading grid paint, I delete all the layers and restart with an empty one to maintain tileset data.
- However this won't be a true reset since zoom, grid size, the currently selected tool, the currently selected tile, etc wouldn't reset.
2. Save and load the old tileset for the newly reloaded grid paint scene.
- However I'm not seeing a straightforward way to do this. I might be missing something, but it seems like the tiles are children nodes of the Tileset GridContainer, so I believe I would have to save the Tileset GridContainer as a PackedScene to save it's current state before reloading the grid paint scene.

Is there a better way that I should go about this or should I go with the second approach?

I apologize for the slow progress, but I think over time I will get the hang of things and I'll speed up :^)

**Comment by ETdoFresh** [comment]
Yeah, I like option 2 alot. But yeah, I didn't think this all the way through. So, for now, just do me a favor... just do the same thing you are doing for **Start complete over** (albeit in a separate function), and right before reloading the scene again, put a comment "# TODO: Load Tileset from resource file". I like your idea of storing this in a resource file. I'm thinking when we click start over using same tileset, we store all the tileset data into **res://resources/tilesets.tres.** But then that has a trickle down effect to, how do we store the texture and tiles? And soooo, all of that also has to be in the tres file.... and I'm not quite ready for that. It'll be its own tasks... Once you get that second function and comment in, submit the PR, and we'll go on from there!

**Comment by onsclom** [comment]
Thanks for splitting up that as a new task! That sounds like a good plan.
