### ISSUE TITLE
Make Delete Smaller and possible a trashcan icon

### ISSUE THREAD

**Issue by ETdoFresh** [ETdoFresh/TileMapCreator#38]
![image](https://user-images.githubusercontent.com/1261843/91512543-db9e7980-e8a7-11ea-88b0-3dec49952a53.png)
This delete icon needs to be about 10-15% of the icon, not like 30-40% like it is now. Maybe change it to a trash can.
**Tileset Scene**

**Comment by onsclom** [comment]
> this comm is great! Thanks! A future task of mine is to redo this crazy grid thing I got going on.... so don't worry too much about the stretching of that button. If possible (don't worry if it's too hard, can you make that trashcan centered?) Additionally, can you make that trash can white? And I think that should do it for this task. Commit and then send PR... if you have questions about how to do any of that, lemme know.

Centering icons on a Button is a feature that isn't supported yet (even though it seems someone has been trying to merge it since 2018 lol [link](https://github.com/godotengine/godot/pull/22006)). I can use a TextureButton instead to get it nicely centered, but we would be losing some of the nice built-in interactibility of regular Buttons like the built in hover and click effects. Would you rather me keep it how it is, or change it to a TextureButton with some extra images for hover and clicked states?

Using a white image is a great idea and I'll be sure to do that.

**Comment by ETdoFresh** [comment]
![image](https://user-images.githubusercontent.com/1261843/91667969-1aae1400-eace-11ea-82e6-6cad01d66641.png)
Use the TextureRectButton Node, I set it up for using TextureRect as buttons and it has a signal too.

**Comment by ETdoFresh** [comment]
If you want the grey background, It'll have to be added to the image? Or we leave it as a regular button and put the trashcan as a child TextureRect so that *most* of the button highlights.... I'll leave that up to you

**Comment by onsclom** [comment]
I liked the TextureRect as a child idea! It looked & worked nicely so I went with that solution.
